//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACash
    {
        public int CID { get; set; }
        public Nullable<System.DateTime> ExchangeDate { get; set; }
        public Nullable<decimal> Cash { get; set; }
        public Nullable<decimal> Note { get; set; }
        public Nullable<decimal> Mz { get; set; }
        public Nullable<int> VoucherId { get; set; }
        public string VoucherType { get; set; }
        public Nullable<int> VoucherYear { get; set; }
        public Nullable<int> VoucherMonth { get; set; }
        public bool VoucherFlag { get; set; }
        public Nullable<decimal> ZJBL1 { get; set; }
        public Nullable<decimal> ZJBL2 { get; set; }
        public Nullable<decimal> ZJBL3 { get; set; }
        public string Ccode { get; set; }
        public string Type { get; set; }
        public Nullable<int> IDTEMP { get; set; }
        public string HDW { get; set; }
    }
}
