//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACLIENTS
    {
        public int CID { get; set; }
        public string CCODE { get; set; }
        public string CNAME { get; set; }
        public string CSHORTCODE { get; set; }
        public string CADDRESS { get; set; }
        public string CTEL { get; set; }
        public string CLINKMAN { get; set; }
        public string CPHONE { get; set; }
        public string CFAXNO { get; set; }
        public string CPOSNO { get; set; }
        public string CBANKNAME { get; set; }
        public string CACCOUNT { get; set; }
        public string CEMAIL { get; set; }
        public string CAREA { get; set; }
        public string CMEMO { get; set; }
        public string CFR { get; set; }
        public string CSH { get; set; }
        public string CBCODE { get; set; }
        public string CFPTEL { get; set; }
        public string CFPBAND { get; set; }
        public string CFPPHONE { get; set; }
        public Nullable<bool> FLAG { get; set; }
    }
}
