//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACONTRACT
    {
        public int HID { get; set; }
        public string HKH { get; set; }
        public string HDW { get; set; }
        public string HCODE { get; set; }
        public string HAREA { get; set; }
        public Nullable<System.DateTime> HDATE { get; set; }
        public string HYWY { get; set; }
        public string HXM { get; set; }
        public Nullable<decimal> HZBJ { get; set; }
        public Nullable<bool> HHS { get; set; }
        public Nullable<int> HHSBL { get; set; }
        public Nullable<decimal> HHTJE { get; set; }
        public Nullable<decimal> HJSJE { get; set; }
        public string HLX { get; set; }
        public string HMEMO { get; set; }
        public string HZT { get; set; }
        public Nullable<System.DateTime> HJHDATE { get; set; }
        public string HUSER { get; set; }
        public string HYHMC { get; set; }
        public string HYHZH { get; set; }
        public string HWTR1 { get; set; }
        public string HWTR2 { get; set; }
        public Nullable<decimal> HYF { get; set; }
        public Nullable<decimal> HQTFY { get; set; }
        public bool FLAG { get; set; }
        public string PS1 { get; set; }
        public string PS2 { get; set; }
        public string PS3 { get; set; }
        public string PS4 { get; set; }
        public string YJ1 { get; set; }
        public string YJ2 { get; set; }
        public string YJ3 { get; set; }
        public string YJ4 { get; set; }
        public string MACODE { get; set; }
        public string MBCODE { get; set; }
        public string MCCODE { get; set; }
        public string MDCODE { get; set; }
        public string MECODE { get; set; }
        public string MFCODE { get; set; }
        public string MGCODE { get; set; }
        public Nullable<decimal> RMB { get; set; }
        public Nullable<decimal> FP { get; set; }
        public Nullable<decimal> GY { get; set; }
        public Nullable<decimal> DLF { get; set; }
        public Nullable<decimal> XXF { get; set; }
        public Nullable<decimal> BSF { get; set; }
        public Nullable<System.DateTime> QDRQ { get; set; }
        public string ZBFS { get; set; }
        public string WXState { get; set; }
        public string BIDCODE { get; set; }
    }
}
