//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFKXX
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> rmb { get; set; }
        public string hth { get; set; }
        public string xshth { get; set; }
        public string type { get; set; }
        public string fkfs { get; set; }
        public string fklx { get; set; }
        public Nullable<bool> flag { get; set; }
        public Nullable<int> vid { get; set; }
        public string vtype { get; set; }
        public Nullable<int> vyear { get; set; }
        public Nullable<int> vmonth { get; set; }
        public Nullable<decimal> bl1 { get; set; }
        public Nullable<decimal> bl2 { get; set; }
        public Nullable<decimal> bl3 { get; set; }
        public Nullable<int> CID { get; set; }
    }
}
