//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContractEntities : DbContext
    {
        public ContractEntities()
            : base("name=ContractEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Org_Depts> Org_Depts { get; set; }
        public virtual DbSet<Org_Emps> Org_Emps { get; set; }
        public virtual DbSet<WF_Nodes> WF_Nodes { get; set; }
        public virtual DbSet<WF_TemRows> WF_TemRows { get; set; }
        public virtual DbSet<WF_Tems> WF_Tems { get; set; }
        public virtual DbSet<V_Emps> V_Emps { get; set; }
        public virtual DbSet<V_Flow_GB_Company> V_Flow_GB_Company { get; set; }
        public virtual DbSet<ACash> ACash { get; set; }
        public virtual DbSet<AFKXX> AFKXX { get; set; }
        public virtual DbSet<Org_Roles> Org_Roles { get; set; }
        public virtual DbSet<ACLIENTS> ACLIENTS { get; set; }
        public virtual DbSet<V_UnfinishedContracts> V_UnfinishedContracts { get; set; }
        public virtual DbSet<AWX> AWX { get; set; }
        public virtual DbSet<WF_CompanyToTem> WF_CompanyToTem { get; set; }
        public virtual DbSet<V_Flow_GB_Customer> V_Flow_GB_Customer { get; set; }
        public virtual DbSet<Sys_Menus> Sys_Menus { get; set; }
        public virtual DbSet<WF_Flow1> WF_Flow1 { get; set; }
        public virtual DbSet<WF_Flow2> WF_Flow2 { get; set; }
        public virtual DbSet<WF_Flows> WF_Flows { get; set; }
        public virtual DbSet<V_Flows> V_Flows { get; set; }
    }
}
