//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Balance
    {
        public long ID { get; set; }
        public string Company { get; set; }
        public Nullable<decimal> Rmb { get; set; }
        public Nullable<decimal> Note { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string 状态 { get; set; }
        public string 类型 { get; set; }
    }
}
