//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CashItem
    {
        public System.Guid CashID { get; set; }
        public Nullable<System.DateTime> ExchangeDate { get; set; }
        public decimal Cash { get; set; }
        public decimal Note { get; set; }
        public string Ccode { get; set; }
        public decimal Mz { get; set; }
        public string Hdw { get; set; }
        public string NCodeC { get; set; }
        public string NCodeN { get; set; }
        public string NCodeCName { get; set; }
        public string NCodeNName { get; set; }
        public string IsFinished { get; set; }
        public string CNAME { get; set; }
        public int ID { get; set; }
        public string Result { get; set; }
        public decimal Cash1 { get; set; }
        public decimal Note1 { get; set; }
        public decimal ContractTotal { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
        public string ApprovalStatusName { get; set; }
        public System.Guid FlowID { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
