//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Chart1
    {
        public string bcode { get; set; }
        public string bname { get; set; }
        public Nullable<decimal> cash { get; set; }
        public Nullable<decimal> note { get; set; }
        public Nullable<decimal> mnote { get; set; }
        public Nullable<decimal> total { get; set; }
    }
}
