//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Flow_GB_Customer
    {
        public Nullable<System.Guid> CashID { get; set; }
        public string CustomerID { get; set; }
        public string Customer { get; set; }
        public string RoleID { get; set; }
        public decimal Total { get; set; }
        public string CompanyID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string IsFinished { get; set; }
    }
}
