//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Flows
    {
        public System.Guid FID { get; set; }
        public string FName { get; set; }
        public Nullable<int> CurNode { get; set; }
        public string IsFinished { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Creater { get; set; }
        public Nullable<System.Guid> TemID { get; set; }
        public int Expr1 { get; set; }
        public string HCode { get; set; }
        public Nullable<decimal> CurRmb { get; set; }
        public string Customer { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public Nullable<decimal> CTotal { get; set; }
        public string CType { get; set; }
        public Nullable<decimal> Rmb { get; set; }
        public Nullable<decimal> Voice { get; set; }
        public string Saleman { get; set; }
        public string CTypeID { get; set; }
        public string CustomerID { get; set; }
        public string CompanyID { get; set; }
        public string SalemanID { get; set; }
        public string BidCode { get; set; }
        public string BidType { get; set; }
        public string TemName { get; set; }
        public string TemIsEnabled { get; set; }
        public Nullable<int> RID { get; set; }
        public string RName { get; set; }
        public Nullable<int> NextID { get; set; }
        public Nullable<int> PreID { get; set; }
        public string NextNode { get; set; }
        public string PreNode { get; set; }
    }
}
