//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_UnfinishedContracts
    {
        public string HCODE { get; set; }
        public string CustomerID { get; set; }
        public Nullable<decimal> Total { get; set; }
        public decimal RMB { get; set; }
        public decimal INV { get; set; }
        public Nullable<decimal> NonRmb { get; set; }
        public Nullable<decimal> NonInv { get; set; }
        public string XSHCODE { get; set; }
        public string Category { get; set; }
        public string CompanyID { get; set; }
        public string BIDCODE { get; set; }
    }
}
