//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WF3_HVoucher
    {
        public System.Guid FlowID { get; set; }
        public string VoucherID { get; set; }
        public string HID { get; set; }
        public int year { get; set; }
        public short month { get; set; }
        public string vtype { get; set; }
        public int vno { get; set; }
    }
}
