//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vcontracts
    {
        public string 项目名称 { get; set; }
        public string 客户名 { get; set; }
        public string 合同号 { get; set; }
        public Nullable<System.DateTime> 签定日期 { get; set; }
        public Nullable<decimal> 合同金额 { get; set; }
        public Nullable<decimal> 结算金额 { get; set; }
        public Nullable<decimal> 质保金 { get; set; }
        public Nullable<decimal> 运费 { get; set; }
        public Nullable<decimal> 其它费用 { get; set; }
        public string 合同类型 { get; set; }
        public Nullable<decimal> 金额 { get; set; }
        public Nullable<decimal> 发票 { get; set; }
        public Nullable<decimal> 金额1 { get; set; }
        public Nullable<decimal> 发票1 { get; set; }
        public Nullable<decimal> 估验 { get; set; }
        public Nullable<decimal> 财务余额 { get; set; }
        public string 地区 { get; set; }
        public string 合同备注 { get; set; }
        public string 业务员 { get; set; }
        public string 状态 { get; set; }
        public Nullable<System.DateTime> 交货日期 { get; set; }
        public string 操作员 { get; set; }
        public string 银行名称 { get; set; }
        public string 账号 { get; set; }
        public string 对方委托人 { get; set; }
        public string 己方委托人 { get; set; }
        public Nullable<bool> 含税 { get; set; }
        public Nullable<int> 比例 { get; set; }
        public string 部门主管 { get; set; }
        public string 财务主管 { get; set; }
        public string 公司主管 { get; set; }
        public string 审计主管 { get; set; }
        public string 部门意见 { get; set; }
        public string 财务意见 { get; set; }
        public string 公司意见 { get; set; }
        public string 审计意见 { get; set; }
        public string MACODE { get; set; }
        public string MBCODE { get; set; }
        public string MCCODE { get; set; }
        public string MDCODE { get; set; }
        public string MECODE { get; set; }
        public string MFCODE { get; set; }
        public string MGCODE { get; set; }
        public bool FLAG { get; set; }
        public string HAREA { get; set; }
        public string HLX { get; set; }
        public string HKH { get; set; }
        public string HYWY { get; set; }
        public string HDW { get; set; }
        public int HID { get; set; }
        public Nullable<decimal> 代理费 { get; set; }
        public Nullable<decimal> 选型费 { get; set; }
        public Nullable<decimal> 标书费 { get; set; }
        public string 公司名 { get; set; }
        public Nullable<System.DateTime> 签订日期 { get; set; }
        public string 中标方式 { get; set; }
        public string WXState { get; set; }
        public string 标号 { get; set; }
    }
}
