//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_Flow3
    {
        public System.Guid FlowID { get; set; }
        public Nullable<System.DateTime> ExchangeDate { get; set; }
        public Nullable<decimal> Rmb { get; set; }
        public string CompanyID { get; set; }
        public string CashItem { get; set; }
        public string VoucherID { get; set; }
        public string NoteItem { get; set; }
        public Nullable<decimal> Note { get; set; }
        public string VoucherID1 { get; set; }
    }
}
