//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WF_Flow1
    {
        public int FID { get; set; }
        public Nullable<decimal> Rmb { get; set; }
        public string HCode { get; set; }
        public Nullable<System.Guid> FlowID { get; set; }
        public Nullable<System.Guid> CashID { get; set; }
        public string XSHcode { get; set; }
    }
}
